package models

// imports
import (
	"time";
	"go.mongodb.org/mongo-driver/bson/primitive";
)

// task item
type Task struct {
	ID            primitive.ObjectID    `bson:"_id,omitempty" json:"id"`                                     // unique identifier of task generated by mongodb
	Title         string                `bson:"title" json:"title"`                  		                    // title of task
	Description   string                `bson:"description" json:"description"`    					               // description of task
	DueDate       time.Time             `bson:"due_date" json:"due_date"`  		                                      // due date of task (ISO 8601 format)
	Status        string      			`bson:"status" json:"status" binding:"oneof=pending in_progress completed"`       // status of task
}